# fly.toml app configuration file generated for purrlay on 2025-08-27T00:38:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'purrlay'
primary_region = 'ewr'

[build]

[http_service]
internal_port = 8081
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

# WebSockets (separate port)
[[services]]
    internal_port = 6942
    protocol = "tcp"
    processes = ["app"]

[[services.ports]]
    port = 6942
    handlers = ["tls"]

# UDP service (example: port 7777)
[[services]]
  internal_port = 7777
  protocol = "udp"
  processes = ["app"]

[[services.ports]]
  port = 7777

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
